export type WorldDefinition = {
  slug: string;
  order: number;
  title: string;
  subtitle: string;
  description: string;
  icon: string; // lucide-react icon name
  colorFrom: string;
  colorTo: string;
  lessonCount: number;
  estimatedHours: number;
};

/**
 * The 25 CodeQuest worlds. `lessonCount` seeds how many nodes generators
 * create per world (15-40, per spec) — tuned per topic depth.
 */
export const WORLDS: WorldDefinition[] = [
  {
    slug: "claude-basics",
    order: 1,
    title: "Claude Basics",
    subtitle: "Meet your AI pair programmer",
    description:
      "Start here: what Claude is, how conversations work, and how to get useful answers fast.",
    icon: "Sparkles",
    colorFrom: "#FF7A1A",
    colorTo: "#FFC857",
    lessonCount: 18,
    estimatedHours: 4,
  },
  {
    slug: "prompt-engineering",
    order: 2,
    title: "Prompt Engineering",
    subtitle: "Speak the model's language",
    description:
      "Structure, context, examples, and iteration — the craft of writing prompts that work.",
    icon: "MessageSquareText",
    colorFrom: "#FF7A1A",
    colorTo: "#FF9E3D",
    lessonCount: 24,
    estimatedHours: 6,
  },
  {
    slug: "claude-code",
    order: 3,
    title: "Claude Code",
    subtitle: "Agentic coding in your terminal",
    description:
      "Tools, permissions, plan mode, subagents, hooks, and building real features end-to-end.",
    icon: "TerminalSquare",
    colorFrom: "#FF7A1A",
    colorTo: "#FFC857",
    lessonCount: 32,
    estimatedHours: 10,
  },
  {
    slug: "git",
    order: 4,
    title: "Git",
    subtitle: "Version control that never loses work",
    description: "Commits, branches, merges, rebases, and recovering from mistakes.",
    icon: "GitBranch",
    colorFrom: "#F97316",
    colorTo: "#FFC857",
    lessonCount: 22,
    estimatedHours: 5,
  },
  {
    slug: "github",
    order: 5,
    title: "GitHub",
    subtitle: "Collaborate at scale",
    description: "Pull requests, code review, Actions, issues, and open-source workflows.",
    icon: "FolderGit2",
    colorFrom: "#FF7A1A",
    colorTo: "#FF9E3D",
    lessonCount: 20,
    estimatedHours: 5,
  },
  {
    slug: "terminal",
    order: 6,
    title: "Terminal",
    subtitle: "The command line, demystified",
    description: "Navigation, piping, permissions, processes, and shell scripting basics.",
    icon: "SquareTerminal",
    colorFrom: "#FF7A1A",
    colorTo: "#FFC857",
    lessonCount: 18,
    estimatedHours: 4,
  },
  {
    slug: "linux",
    order: 7,
    title: "Linux",
    subtitle: "Run the machines everything runs on",
    description: "Filesystems, users, systemd, networking basics, and package management.",
    icon: "Server",
    colorFrom: "#F97316",
    colorTo: "#FFC857",
    lessonCount: 24,
    estimatedHours: 6,
  },
  {
    slug: "vscode",
    order: 8,
    title: "VS Code",
    subtitle: "Your editor, tuned to fly",
    description: "Shortcuts, extensions, debugging, multi-cursor, and workspace config.",
    icon: "Code2",
    colorFrom: "#FF7A1A",
    colorTo: "#FF9E3D",
    lessonCount: 16,
    estimatedHours: 3,
  },
  {
    slug: "react",
    order: 9,
    title: "React",
    subtitle: "Components, state, and the DOM",
    description: "Hooks, composition, rendering behavior, and building real UIs.",
    icon: "Atom",
    colorFrom: "#FF7A1A",
    colorTo: "#FFC857",
    lessonCount: 34,
    estimatedHours: 10,
  },
  {
    slug: "nextjs",
    order: 10,
    title: "Next.js",
    subtitle: "The full-stack React framework",
    description: "App Router, server components, data fetching, and deployment.",
    icon: "Layers",
    colorFrom: "#FF7A1A",
    colorTo: "#FF9E3D",
    lessonCount: 30,
    estimatedHours: 9,
  },
  {
    slug: "javascript",
    order: 11,
    title: "JavaScript",
    subtitle: "The language of the web",
    description: "Closures, async, prototypes, and the parts that trip everyone up.",
    icon: "Braces",
    colorFrom: "#FFC857",
    colorTo: "#FF9E3D",
    lessonCount: 32,
    estimatedHours: 9,
  },
  {
    slug: "typescript",
    order: 12,
    title: "TypeScript",
    subtitle: "Types that catch bugs before runtime",
    description: "Generics, narrowing, utility types, and typing real-world APIs.",
    icon: "FileType2",
    colorFrom: "#FF7A1A",
    colorTo: "#FFC857",
    lessonCount: 26,
    estimatedHours: 7,
  },
  {
    slug: "nodejs",
    order: 13,
    title: "Node.js",
    subtitle: "JavaScript on the server",
    description: "The event loop, streams, the module system, and building CLIs.",
    icon: "Cpu",
    colorFrom: "#FF7A1A",
    colorTo: "#FF9E3D",
    lessonCount: 22,
    estimatedHours: 6,
  },
  {
    slug: "apis",
    order: 14,
    title: "APIs",
    subtitle: "Systems that talk to each other",
    description: "REST, GraphQL, webhooks, rate limits, and designing clean contracts.",
    icon: "Plug",
    colorFrom: "#F97316",
    colorTo: "#FFC857",
    lessonCount: 20,
    estimatedHours: 5,
  },
  {
    slug: "sql",
    order: 15,
    title: "SQL",
    subtitle: "Ask questions of your data",
    description: "Joins, aggregates, indexes, and writing queries that scale.",
    icon: "Table2",
    colorFrom: "#FF7A1A",
    colorTo: "#FFC857",
    lessonCount: 24,
    estimatedHours: 6,
  },
  {
    slug: "postgresql",
    order: 16,
    title: "PostgreSQL",
    subtitle: "A serious relational database",
    description: "Schema design, transactions, constraints, and performance tuning.",
    icon: "Database",
    colorFrom: "#FF7A1A",
    colorTo: "#FF9E3D",
    lessonCount: 22,
    estimatedHours: 6,
  },
  {
    slug: "supabase",
    order: 17,
    title: "Supabase",
    subtitle: "Postgres, batteries included",
    description: "Auth, storage, edge functions, and row-level security in practice.",
    icon: "Flame",
    colorFrom: "#FF7A1A",
    colorTo: "#FFC857",
    lessonCount: 20,
    estimatedHours: 5,
  },
  {
    slug: "authentication",
    order: 18,
    title: "Authentication",
    subtitle: "Prove who's who, safely",
    description: "Sessions, tokens, OAuth, magic links, and 2FA done right.",
    icon: "ShieldCheck",
    colorFrom: "#F97316",
    colorTo: "#FFC857",
    lessonCount: 18,
    estimatedHours: 5,
  },
  {
    slug: "mcp",
    order: 19,
    title: "MCP",
    subtitle: "Give models real tools",
    description: "The Model Context Protocol: servers, resources, and connecting Claude to anything.",
    icon: "Workflow",
    colorFrom: "#FF7A1A",
    colorTo: "#FF9E3D",
    lessonCount: 20,
    estimatedHours: 6,
  },
  {
    slug: "ai-agents",
    order: 20,
    title: "AI Agents",
    subtitle: "Systems that plan and act",
    description: "Tool use, memory, planning loops, and multi-agent orchestration.",
    icon: "Bot",
    colorFrom: "#FF7A1A",
    colorTo: "#FFC857",
    lessonCount: 26,
    estimatedHours: 8,
  },
  {
    slug: "automation",
    order: 21,
    title: "Automation",
    subtitle: "Make the computer do the boring parts",
    description: "Hooks, cron, CI triggers, and scripting repeatable workflows.",
    icon: "Zap",
    colorFrom: "#FFC857",
    colorTo: "#FF7A1A",
    lessonCount: 18,
    estimatedHours: 5,
  },
  {
    slug: "testing",
    order: 22,
    title: "Testing",
    subtitle: "Ship without fear",
    description: "Unit, integration, and end-to-end tests — and what's worth testing at all.",
    icon: "FlaskConical",
    colorFrom: "#FF7A1A",
    colorTo: "#FF9E3D",
    lessonCount: 20,
    estimatedHours: 6,
  },
  {
    slug: "deployment",
    order: 23,
    title: "Deployment",
    subtitle: "Get code in front of users",
    description: "CI/CD, environments, rollbacks, and zero-downtime releases.",
    icon: "Rocket",
    colorFrom: "#FF7A1A",
    colorTo: "#FFC857",
    lessonCount: 18,
    estimatedHours: 5,
  },
  {
    slug: "scaling",
    order: 24,
    title: "Scaling",
    subtitle: "When one server isn't enough",
    description: "Caching, queues, load balancing, and finding real bottlenecks.",
    icon: "TrendingUp",
    colorFrom: "#F97316",
    colorTo: "#FFC857",
    lessonCount: 16,
    estimatedHours: 5,
  },
  {
    slug: "startup-engineering",
    order: 25,
    title: "Startup Engineering",
    subtitle: "Ship a real product",
    description:
      "The capstone world: taking an idea from zero to a deployed, monetized product.",
    icon: "Crown",
    colorFrom: "#FFC857",
    colorTo: "#FF7A1A",
    lessonCount: 20,
    estimatedHours: 8,
  },
];

export function getWorldBySlug(slug: string) {
  return WORLDS.find((w) => w.slug === slug);
}

export function getNextWorld(order: number) {
  return WORLDS.find((w) => w.order === order + 1);
}
